FROM golang:1.21.3-alpine as builder
RUN apk --no-cache add gcc g++ libtool musl-dev librdkafka-dev pkgconf
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN CGO_ENABLED=1 GOOS=linux go build -tags musl -a -o consumer consumer/consumer.go

FROM alpine:3.18.4 as runtime
COPY --from=builder /app/consumer /
EXPOSE 8080
CMD ["/bin/sh", "-c", "/consumer"]
